#!/bin/bash

url="https://pokeapi.co/api/v2/pokewwwmon/ditto"

echo "Reaching the server to get the data..."

resource=$(curl -s -X GET $url)

if [$? -ne 0]; then
    echo "Request failed to fetch data from $url" >> errors.txt
    exit 1 
fi 

echo "This is the data from Pokemon"
echo "$resource" | jq. > data.json